-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-------------------------
-- SOURCE OTHER FILES --
-------------------------

require("conf.env")

require("monitors")
require("workspaces")

require("conf.program_var")
require("conf.permissions")
require("conf.dark_mode")
require("conf.startup")
require("conf.window_rules")
require("conf.input_devices")
require("conf.look_and_feel")
require("conf.keybinding")
require("conf.shutdown")
require("conf.plugins")
