-- Generated by nwg-displays on 2026-08-07 at 18:48:34. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x89B2",
    mode = "2240x1400@60.0",
    position = "1307x3180",
    scale = 1.0
})
hl.monitor({
    output = "desc:Nreal Air 0x88888800",
    mode = "1920x1080@60.0",
    position = "1482x2100",
    scale = 1.0
})
