-- Generated by nwg-displays on 2026-07-01 at 13:04:18. Do not edit manually.

hl.monitor({
    output = "desc:Lenovo Group Limited 0x89B2",
    mode = "2240x1400@60.0",
    position = "0x2460",
    scale = 1.0
})
hl.monitor({
    output = "desc:Microstep MSI MAG272C 0x30303453",
    disabled = true
})
hl.monitor({
    output = "desc:AOC 24G2WG3- PIPM4JA006993",
    disabled = true
})
hl.monitor({
    output = "desc:Dell Inc. DELL U2415 08DXD4AP0TAL",
    disabled = true
})
