context.modules = [
  {
    name = libpipewire-module-parametric-equalizer
    args = {
      equalizer.filepath = "/home/rasmus/.config/pipewire/eq/soundcore_c30i.txt"
      equalizer.description = "Soundcore C30i headphone EQ"
      audio.channels = 2
      audio.position = [ FL FR ]
    }
  }
]
