-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- DARK MODE

hl.env("GDK_BACKEND", "wayland")

-- GTK

hl.env("GTK_THEME", "Adwaita:dark")

-- Qt

hl.env("QT_QPA_PLATFORMTHEME", "qt5ct")
hl.env("QT_QUICK_CONTROLS_STYLE", "org.kde.desktop")

-- Exec (run every reload)
hl.on("config.reloaded", function()
	hl.exec_cmd("gsettings set org.gnome.desktop.interface gtk-theme Adwaita-Dark")
	hl.exec_cmd("gsettings set org.gnome.desktop.interface color-scheme prefer-dark")
end)
