-- Generated by hyprconf2lua v1.4.
-- https://github.com/Prateek-squadron/hyprconf2lu
-- Manual review may be needed for complex directives

---@module 'hl'

-- KEYBINDINGS

local settings = "foot -e nvim ~/.config/hypr/"
local fileManager = "nemo"
local menu = "fuzzel"
local calculator = "gnome-calculator"
local browser = "zen-browser"
local browser_private = "zen-browser --private-window"
local browser_lenny = "zen-browser --private-window https://www.lennyfaceguru.com/"
local email = "betterbird"
local discord = "com.discordapp.Discord"

-- -- See https://wiki.hyprland.org/Configuring/Keywords/
local mainMod = "SUPER" -- Sets "Windows" key as main modifier
local mainModShift = "SUPER + SHIFT"
local mainModCtrl = "SUPER + CTRL"
local mainModAlt = "SUPER + ALT"
local mainModAltShift = "SUPER + ALT + SHIFT"
local mainModCtrlShift = "SUPER + CTRL + SHIFT"
local mainModCtrlAlt = "SUPER + CTRL + ALT"
local newTerminal = "footclient -e"
local newTerminalHold = "footclient -e --hold"
local specialExec = "hyprctl dispatch exec [workspace special] foot -e"

-- Bind functions
local function buildKeybind(mod, key)
	if mod == "" then
		return key
	else
		return mod .. " + " .. key
	end
end

local function bindExec(mod, key, cmd, flags)
	hl.bind(buildKeybind(mod, key), hl.dsp.exec_cmd(cmd), flags)
end

local function bindDsp(mod, key, dispatcher, flags)
	hl.bind(buildKeybind(mod, key), dispatcher, flags)
end

local function bindFunc(mod, key, func)
	hl.bind(buildKeybind(mod, key), func)
end

-- Keyboard shortcuts: https://wiki.hyprland.org/Configuring/Binds/
bindExec("XF86Calculator", "", calculator)
bindExec(mainMod, "Escape", "~/.config/hypr/scripts/hypr-blank.sh && notify-send Escaped") -- Moves all monitors to a blank screen
bindExec(
	mainModCtrl,
	"A",
	[[~/.config/hypr/scripts/jump-or-launch-app.sh -l pavucontrol -c org.pulseaudio.pavucontrol -p 'Volume Control' -i 󰕾]]
) -- Audio (device) control

bindExec(mainMod, "B", browser) -- zen
bindExec(mainModAlt, "B", "blender") -- Blender
bindExec(mainModCtrl, "B", "~/.config/hypr/scripts/bt-connect-menu.sh") -- BT Connection menu
bindExec(mainModShift, "B", browser_private) -- zen (private window)
bindExec(
	mainModCtrlAlt,
	"B",
	[[~/.config/hypr/scripts/jump-or-launch-app.sh -l blueman-manager -p 'Bluetooth manager' -i 󰂯]]
)
bindExec(mainModCtrlShift, "B", "~/.config/hypr/scripts/toggle-bluetooth.sh") -- Toggle Bluetooth

bindExec(mainMod, "C", "code") -- VSCode
bindDsp(mainModAlt, "C", hl.dsp.cursor.move_to_corner({ corner = 1 }))
-- TODO: manual review (unknown dispatcher) -- old bind: $mainModAlt, C, movecursortocorner, 1 (bottom right)
bindExec(mainModCtrl, "C", "swaync-client -C") -- Close all notifications
bindExec(mainModShift, "C", "cliphist list| fuzzel --dmenu| cliphist decode| wl-copy") -- Clipboard view

bindExec(mainMod, "D", menu) -- fuzzel
bindExec(mainModShift, "D", "~/.config/hypr/scripts/list-open-apps.sh") -- List open software in fuzzel
bindExec(mainModAlt, "D", [[~/.config/hypr/scripts/jump-or-launch-app.sh -l local_var_discord -c 'discord' -i 󰙯]]) -- Discord

bindExec(
	mainMod,
	"E",
	[[~/.config/hypr/scripts/jump-or-launch-app.sh -l betterbird -c eu.betterbird.Betterbird -p Betterbird -i 󰇮]]
) -- Email client
bindExec(mainModShift, "E", "~/.config/hypr/scripts/emoji-picker.sh copy") -- Emoji picker

bindExec(mainMod, "F", fileManager)
bindExec(mainModAlt, "F", "footclient -e yazi") -- Terminal file manager (yazi)
bindExec(mainModShift, "F", "footclient -e fzf -e") -- Fuzzy search
bindDsp(mainModCtrl, "F", hl.dsp.window.float())

bindDsp(mainMod, "H", hl.dsp.window.pseudo()) -- Window "hover"-mode

bindExec(mainMod, "I", settings) -- Settings (nvim)
bindExec(mainModAlt, "I", "code ~/.config/hypr/") -- Settings (code)

bindDsp(mainMod, "J", hl.dsp.layout("togglesplit")) -- Toggles the split (top/side)
bindDsp(mainModCtrl, "J", hl.dsp.layout("swapsplit")) -- Swaps the two halves of the split

bindExec(mainMod, "L", [[~/.config/hypr/scripts/jump-or-launch-app.sh -l 'net.corluma.Corluma' -c 'corluma' -i 󰌵]]) -- Control HUE lights
-- old bind: $mainModAlt, L, exec, notify-send "Lenny" && $browser_lenny  -- Lenny picker in web browser
bindExec(mainModShift, "L", "/home/rasmus/.config/hypr/scripts/lenny-picker.sh") -- Lenny picker (fuzzel)

bindExec(mainMod, "M", [[~/.config/hypr/scripts/jump-or-launch-app.sh -l 'spotify' -c 'Spotify' -i 󰓇]]) -- Spotify
bindExec(mainModCtrl, "M", "toggle-mic-mute") -- Toggle (default) mic mute status
bindExec(mainModShift, "M", [[~/.config/hypr/scripts/jump-or-launch-app.sh -c Beeper -l beeper -p Beeper -i 󰍡]]) -- Beeper
bindExec(mainModCtrlShift, "M", "~/.config/hypr/scripts/toggle-mouse-hold.sh")

bindExec(mainMod, "N", [[~/.config/hypr/scripts/jump-or-launch-app.sh -l 'obsidian' -i 󰎞]])
bindExec(mainModCtrl, "N", "swaync-client -t") -- Toggle the notification panel

bindExec(
	mainMod,
	"O",
	[[notify-send -t 4000 -h string:synchronous:date_time "󰥔 Current Time" "$(date '+%H:%M:%S - %A - %d/%m/%Y')"]]
)
bindExec(mainModShift, "O", "~/.config/hypr/scripts/battery-status-notify.sh") -- Battery of laptop battery
bindExec(mainModAltShift, "O", "~/.config/hypr/scripts/device-battery-status.sh") -- Battery of all devices

bindExec(mainModCtrl, "P", "~/.config/hypr/scripts/power-profile-picker.sh") -- Power profile picker
bindExec(mainModShift, "P", "~/.config/hypr/scripts/ratbag-profile-switcher.sh") -- Change Logitech mouse profile

bindDsp(mainMod, "Q", hl.dsp.window.close()) -- Kill active window
bindDsp(mainModShift, "Q", hl.dsp.window.kill()) -- Kill all similar windows to the active

bindExec(mainModCtrlShift, "R", "hyprctl reload") -- Reload Hyprland

bindExec(mainMod, "S", "hyprctl dispatch exec [workspace special] foot -e btop") -- System monitor
bindDsp(mainModAlt, "S", hl.dsp.workspace.toggle_special(nil))
bindExec(mainModShift, "S", "footclient -e ncdu") -- Disk usage analyzer

bindExec(mainMod, "T", "footclient") -- Terminal
bindExec(mainModShift, "T", fileManager .. " trash://") -- Trash

bindExec(
	mainMod,
	"U",
	[[hyprctl dispatch exec [workspace special] foot -e script -q -O /tmp/system-update-$(date +%Y%m%d-%H%M%S).log -c ~/.config/hypr/scripts/system-update.sh >/dev/null 2>&1]]
) -- Update system
bindExec(
	mainModAlt,
	"U",
	[[hyprctl dispatch exec [workspace special] foot -e script -q -O /tmp/system-alt-update-$(date +%Y%m%d-%H%M%S).log -c ~/.config/hypr/scripts/system-alt-update.sh >/dev/null 2>&1]]
) -- Other system updates

bindExec(mainModCtrl, "V", "~/.config/hypr/scripts/vpn-menu.sh") -- Fuzzel VPN menu

bindExec(mainMod, "W", "~/.config/hypr/scripts/go-to-last-used-workspace.sh") -- Go to last used app
bindExec(
	mainModCtrl,
	"W",
	[[notify-send -h string:synchronous:workspace "󰍹 Workspace: $(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | if .specialWorkspace.id == -99 then "Special" else .activeWorkspace.id end')"]]
) -- Notify the current workspace id
bindExec(mainModShift, "W", "~/.config/hypr/scripts/list-last-used-apps.sh") -- List last used apps in fuzzel
bindExec(mainModCtrlShift, "W", "~/.config/hypr/scripts/hold-key.sh")

-- Move focus with mainMod + arrow keys
local function focusDirection(direction)
	bindDsp(mainMod, direction, hl.dsp.focus({ direction = direction }))
end

-- Focus workspace
local function focusWorkspace(key, workspace)
	bindDsp(mainMod, key, hl.dsp.focus({ workspace = workspace }))
end

-- Move active window to a workspace with mainMod + SHIFT + [0-9]
local function moveWindowToWorkspace(key, workspace)
	bindDsp(mainModShift, key, hl.dsp.window.move({ workspace = workspace }))
end

-- Move whole workspace to another workspace
local function moveWholeWorkspace(key, workspace)
	bindDsp(
		mainModCtrlShift,
		key,
		hl.dsp.exec_cmd("~/.config/hypr/scripts/move-workspace-to-workspace.sh " .. workspace)
	)
end

-- Move window in direction
local function moveWindowDirection(direction)
	bindDsp(mainModShift, direction, hl.dsp.window.move({ direction = direction }))
end

-- TODO: Does not take into account workspace 10 (key 0)
-- Loop add bindings
for i = 1, 10, 1 do
	local key = (i == 10) and "0" or tostring(i)
	focusWorkspace(key, i)
	moveWindowToWorkspace(key, i)
	moveWholeWorkspace(key, i)
end

for _, direction in ipairs({ "left", "right", "up", "down" }) do
	focusDirection(direction)
	moveWindowDirection(direction)
end

-- Groups
hl.bind(mainMod .. " + " .. "g", hl.dsp.group.toggle())
hl.bind(mainModShift .. " + " .. "g", hl.dsp.group.next())

-- TODO: manual review (unknown dispatcher: lockactivegroup
-- hl.bind("$mainModCtrl + g", hl.dsp.lockactivegroup("toggle"))

-- Scroll through existing workspaces with mainMod + scroll
hl.bind(mainMod .. " + " .. "mouse_down", hl.dsp.focus({ workspace = "e+1" }))
hl.bind(mainMod .. " + " .. "mouse_up", hl.dsp.focus({ workspace = "e-1" }))

-- Move/resize windows with mainMod + LMB/RMB and dragging
hl.bind(mainMod .. " + " .. "mouse:272", hl.dsp.window.drag(), { mouse = true })
hl.bind(mainMod .. " + " .. "mouse:273", hl.dsp.window.resize(), { mouse = true })

-- Resize window
local function resizeWindow(direction, x, y)
	bindDsp(mainModCtrl, direction, hl.dsp.window.resize({ x = x, y = y, relative = true }), { repeating = true })
end

resizeWindow("left", -30, 0)
resizeWindow("right", 30, 0)
resizeWindow("up", 0, -30)
resizeWindow("down", 0, 30)

-- Airplane mode notification
hl.bind("XF86RFKill", hl.dsp.exec_cmd("airplane-mode-notify")) -- Power
hl.bind(
	"CTRL + ALT + SHIFT" .. " + " .. "F2",
	hl.dsp.exec_cmd("playerctl -a pause &> /dev/null || systemctl suspend && hyprlock --no-fade-in -q")
) -- suspend
hl.bind("CTRL + ALT + SHIFT" .. " + " .. "F3", hl.dsp.exec_cmd("systemctl reboot")) -- reboot
hl.bind("CTRL + ALT + SHIFT" .. " + " .. "F4", hl.dsp.exec_cmd("systemctl poweroff")) -- poweroff -- Toggle touchpad
hl.bind(mainModCtrl .. " + " .. "T", hl.dsp.exec_cmd("toggle-touchpad"))

-- Hyprland
local screenshot_dir = "~/Pictures/Screenshots"
hl.bind(
	"PRINT",
	hl.dsp.exec_cmd(
		"hyprshot -z -m region -m active -m window -o ~/Pictures/Screenshots -f $(date +'%Y_%m_%d_%H%M%S')_hyprshot_window.png"
	)
) -- Screenshot the active window
hl.bind(
	"CTRL" .. " + " .. "PRINT",
	hl.dsp.exec_cmd("hyprshot -m region -z -o ~/Pictures/Screenshots -f $(date +'%Y_%m_%d_%H%M%S')_hyprshot_region.png")
) -- Screenshot selected area
hl.bind(
	mainMod .. " + " .. "PRINT",
	hl.dsp.exec_cmd(
		"hyprshot -m output -z -o ~/Pictures/Screenshots -f $(date +'%Y_%m_%d_%H%M%S')_hyprshot_monitor.png"
	)
) -- Screenshot whole monitor -- bind = $mainMod, TAB, hyprexpo:expo, toggle  # Hyprspace
hl.bind(mainModCtrl .. " + " .. "S", hl.dsp.exec_cmd("toggle-hyprshade")) -- Toggle hyprshade
hl.bind(mainModCtrlAlt .. " + " .. "S", hl.dsp.exec_cmd("hyprshade on grayscale")) -- Enable grayscale filter

-- Zoom
bindFunc(mainMod, "Z", function()
	local ZOOM_LEVEL = 2.5
	local MIN_ZOOM = 1
	local current_zoom = hl.get_config("cursor.zoom_factor")
	local target = current_zoom == MIN_ZOOM and ZOOM_LEVEL or MIN_ZOOM
	hl.config({ cursor = { zoom_factor = target } })
end)

-- Color picker
bindExec(mainMod, "P", "hyprpicker -a -q && notify-send 󰏘 Color copied to clipboard")

-- Brightness
local function brigthnessControl(mod, key, amount)
	local brightnessNotify =
		[[awk -v cur="$(brightnessctl get)" -v max="$(brightnessctl max)" 'BEGIN { printf("%.0f", cur/max*100) }' | xargs -I{} notify-send -h int:value:{} -h string:synchronous:volume "󰍹 Brightness: {}%"]]
	bindExec(
		mod,
		key,
		"brightnessctl set " .. amount .. "% && " .. brightnessNotify,
		{ repeating = true, locked = true }
	)
end

brigthnessControl("", "XF86MonBrightnessUp", "5+")
brigthnessControl("", "XF86MonBrightnessDown", "5-")
brigthnessControl("SHIFT", "XF86MonBrightnessUp", "30+")
brigthnessControl("SHIFT", "XF86MonBrightnessDown", "30-")
brigthnessControl("CTRL", "XF86MonBrightnessUp", "2+")
brigthnessControl("CTRL", "XF86MonBrightnessDown", "2-")

-- Media control
-- Volume: Notifications
local media_mute_notify =
	"pactl get-sink-mute @DEFAULT_SINK@| grep -q 'yes' && notify-send -t 2000 -h string:synchronous:volume 󰝟 Muted || notify-send -t 2000 -h string:synchronous:volume 󰕾 Unmuted"
local mic_mute_notify =
	"pactl get-source-mute @DEFAULT_SOURCE@| grep -q 'yes' && notify-send -t 2000 -h string:synchronous:mic-mute 󰍭 Muted || notify-send -t 2000 -h string:synchronous:mic-mute 󰍬 Unmuted"

-- Volume
local function volumeControl(mod, key, amount)
	local volumeNotify =
		[[wpctl get-volume @DEFAULT_AUDIO_SINK@ | awk '{print $2*100}' | xargs -I{} notify-send -t 1000 -h int:value:{} -h string:synchronous:volume "󰕾 Volume: {}%"]]
	bindExec(
		mod,
		key,
		"wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ " .. amount .. " && " .. volumeNotify,
		{ repeating = true, locked = true }
	)
end

volumeControl("", "XF86AudioRaiseVolume", "5%+")
volumeControl("", "XF86AudioLowerVolume", "5%-")
volumeControl("CTRL", "XF86AudioRaiseVolume", "1%+")
volumeControl("CTRL", "XF86AudioLowerVolume", "1%-")
volumeControl("SHIFT", "XF86AudioRaiseVolume", "10%+")
volumeControl("SHIFT", "XF86AudioLowerVolume", "10%-")
volumeControl(mainModAlt, "up", "2%+")
volumeControl(mainModAlt, "down", "2%-")

-- Mute media
hl.bind(
	"XF86AudioMute",
	hl.dsp.exec_cmd(
		"wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && pactl get-sink-mute @DEFAULT_SINK@| grep -q 'yes' && notify-send -t 2000 -h string:synchronous:volume 󰝟 Muted || notify-send -t 2000 -h string:synchronous:volume 󰕾 Unmuted"
	),
	{ locked = true }
)
hl.bind(
	mainModCtrlShift .. " + " .. "O",
	hl.dsp.exec_cmd(
		"wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle && pactl get-sink-mute @DEFAULT_SINK@| grep -q 'yes' && notify-send -t 2000 -h string:synchronous:volume 󰝟 Muted || notify-send -t 2000 -h string:synchronous:volume 󰕾 Unmuted"
	),
	{ locked = true }
)

-- Mute mic
hl.bind(
	"XF86AudioMicMute",
	hl.dsp.exec_cmd(
		"wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && pactl get-source-mute @DEFAULT_SOURCE@| grep -q 'yes' && notify-send -t 2000 -h string:synchronous:mic-mute 󰍭 Muted || notify-send -t 2000 -h string:synchronous:mic-mute 󰍬 Unmuted"
	),
	{ locked = true }
)
hl.bind(
	mainModCtrlShift .. " + " .. "I",
	hl.dsp.exec_cmd(
		"wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle && pactl get-source-mute @DEFAULT_SOURCE@| grep -q 'yes' && notify-send -t 2000 -h string:synchronous:mic-mute 󰍭 Muted || notify-send -t 2000 -h string:synchronous:mic-mute 󰍬 Unmuted"
	),
	{ locked = true }
)

-- Play-pause
local function playPauseToggle(mod, key)
	bindExec(mod, key, "playerctl play-pause", { locked = true })
end
playPauseToggle("", "XF86AudioPause")
playPauseToggle("", "XF86AudioPlay")
playPauseToggle("ALT", "SPACE")

hl.bind("CTRL + ALT" .. " + " .. "P", hl.dsp.exec_cmd("playerctl -a pause"))
hl.bind("CTRL + ALT" .. " + " .. "SPACE", hl.dsp.exec_cmd("~/.config/hypr/scripts/toggle-selected-player.sh"))

--  Previous-Next
hl.bind("XF86AudioNext", hl.dsp.exec_cmd("playerctl next"), { locked = true })
hl.bind("XF86AudioPrev", hl.dsp.exec_cmd("playerctl previous"), { locked = true })
hl.bind(mainModAlt .. " + " .. "right", hl.dsp.exec_cmd("playerctl next"))
hl.bind(mainModAlt .. " + " .. "left", hl.dsp.exec_cmd("playerctl previous"))

-- Position
hl.bind(mainMod .. " + " .. "PERIOD", hl.dsp.exec_cmd("playerctl position 5+"))
hl.bind(mainMod .. " + " .. "COMMA", hl.dsp.exec_cmd("playerctl position 5-"))
hl.bind(mainModShift .. " + " .. "PERIOD", hl.dsp.exec_cmd("playerctl position 30+"))
hl.bind(mainModShift .. " + " .. "COMMA", hl.dsp.exec_cmd("playerctl position 30-"))

-- Change input/output audio device
hl.bind(mainModCtrl .. " + " .. "O", hl.dsp.exec_cmd("~/.config/hypr/scripts/change-audio-output.sh"))
hl.bind(mainModCtrl .. " + " .. "I", hl.dsp.exec_cmd("~/.config/hypr/scripts/change-audio-input.sh"))

-- CLAMSHELL MODE #
hl.bind(mainModCtrl .. " + " .. "SHIFT" .. " + " .. "E", hl.dsp.exec_cmd("clamshell open")) -- Enable the main display
hl.bind(mainModCtrl .. " + " .. "SHIFT" .. " + " .. "D", hl.dsp.exec_cmd("clamshell closed")) -- Disable the main display
hl.bind("switch:off:Lid Switch", hl.dsp.exec_cmd("clamshell open"), { locked = true })
hl.bind("switch:on:Lid Switch", hl.dsp.exec_cmd("clamshell closed"), { locked = true })

-- TRACKPAD GESTURE #
-- TODO: manual review: gesture = 3, "horizontal", "workspace"
