-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

local function plugin_config(name, opts)
	if hl.plugin[name] then
		hl.config({ plugin = { [name] = opts } })
	end
end

plugin_config("dynamic_cursors", {
	enabled = true,
	mode = "stretch",
	stretch = {
		limit = 4000,
		activation = "linear",
	},
	shake = {
		enabled = false,
	},
})
