-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- MY PROGRAMS

-- See https://wiki.hyprland.org/Configuring/Keywords/

-- Set programs that you use
local terminal = "foot"
local settings = "foot -e nvim ~/.config/hypr/"
local fileManager = "nemo"
local menu = "fuzzel"
local calculator = "gnome-calculator"
local browser = "zen-browser"
local browser_private = "zen-browser --private-window"
local browser_lenny = "zen-browser --private-window https://www.lennyfaceguru.com/"
local email = "betterbird"
local discord = "com.discordapp.Discord"
