-- Generated by hyprconf2lua v1.4.0
-- https://github.com/Prateek-squadron/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'

-- Will execute only on shutdown

-- Shutdown
hl.on("hyprland.shutdown", function()
    hl.exec_cmd("hyprctl keyword device[msft0001:00-06cb:ce44-touchpad]:enabled 1")
end)
